gloo/common/aligned_allocator.h: switch to the one-arg allocate function, dropping const_pointer reference
Summary:
This avoids the following errors:

  buck-out/v2/gen/fbcode/d5479947763d4841/gloo/common/__common__/headers/gloo/common/aligned_allocator.h:53:38: error: no type named 'const_pointer' in 'std::allocator<void>'

Reviewed By: r-barnes

Differential Revision: D37416148

fbshipit-source-id: 9dd57b43716046b4d1c6535f2b68360154eb8fda